version: 1.2.{build}
#branches:
#  only:
#    - master
#    - dev
#    - debug

skip_tags: true

#image: WMF 5
# Test ne build image:
image: Visual Studio 2017

# Install pester module and init the Appveyor support.
install:
  - ps: |
      Install-PackageProvider -Name NuGet -MinimumVersion '2.8.5.201' -Force -Verbose
      Import-PackageProvider NuGet -MinimumVersion '2.8.5.201' -Force
      Install-Module -Name 'Pester' -Scope CurrentUser -RequiredVersion '4.10.1' -Force -SkipPublisherCheck -AllowClobber -Verbos
      Install-Module -Name 'posh-git' -Scope CurrentUser -RequiredVersion '0.7.3' -Force -SkipPublisherCheck -AllowClobber -AllowPrerelease
      Import-Module -Name 'Pester', 'posh-git'
      Import-Module .\tools\AppVeyor.psm1

environment:
  NuGetToken:
    secure: 835qfZIkC9mE7QhkYfOZVAdR8rZhPvxG8BO4CbeaelRQOhlqmaSr8G1DWRJzZ/bS
  CoverallsToken:
    secure: LQIBuPBCk/omFbFhdodb3xo/YU5M4Qd/nlYcBCVUmt9NNU1VJB2IbR8XgJ5b9kMZ
  TestToken:
    secure: lTmOvWgFv59+EEiDkjwJAkMAzXA9y3jidUnz+ZqPS2RXG6UHTWLRTkewS9zDnsHJ
  CodeCovToken:
    secure: KKdzsy/3JetmZtVisZrXnlRjKt6XHkCMgCNn3QnIIOfw1I9iWphkjesTDqAzwX5k

build: false

before_build:
  - ps: Invoke-AppVeyorBumpVersion

build_script:
  - ps: Invoke-AppVeyorBuild

test_script:
  - ps: |
      $CodeCoverage = Invoke-AppVeyorTests
      if ($null -ne $Env:CoverallsToken) {
        Invoke-CoverageReport -PesterCoverageReport $CodeCoverage
      }
      else {
        Write-Warning "No CoverallsToken found. This build seems to be triggered by a PR. Skipping this step..."
      }
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      Invoke-Expression "bash codecov.sh -f 'coverage.xml' -t $Env:CodeCovToken" 2>&1

#after_test:
#  - ps: |
#      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
#      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
#      bash codecov.sh -f "coverage.xml" -t $Env:CodeCovToken

deploy:
  - provider: GitHub
    auth_token:
      secure: M+bBX5/nKdJB0eViP7xtrLVTwf3vGDUA9N2MMprZp2i+9ZR3CBVcJnSzJWUmalhB
    artifact: PSCoverage.zip # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master # release from master branch only

after_deploy:
  - ps: Invoke-AppVeyorPSGallery
